<?php


namespace App\Models\Admin;

use Illuminate\Database\QueryException;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Request;
use App\Models\VegetableNumber as Base;

class VegetableNumber extends Base
{
    const CREATED_AT = 'create_time';
    const UPDATED_AT = null;
    protected $dateFormat = 'U';
    protected $casts = [
        'create_time' => 'datetime:Y-m-d H:i:s',
    ];
    protected $table = "vegetable_number";


    public function creatNumber()
    {
        try {
            DB::beginTransaction();
            $this->number = Request::get('number');
            $this->land_id = Request::get('land_id');

            $this->save();
            DB::commit();
            return true;
        } catch (QueryException $e) {
            DB::rollBack();
            return $e->getMessage();
        }
    }

    public function editNumber()
    {
        try {
            DB::beginTransaction();
            $number = $this->find(Request::input('id'));
            $this->number = Request::get('number');
            $this->land_id = Request::get('land_id');

            $number->save();
            DB::commit();
            return true;
        } catch (QueryException $e) {
            DB::rollBack();
            return $e->getMessage();
        }
    }

    static function page()
    {
        return 'ok'; // TODO: Change the autogenerated stub
    }

    function land()
    {
        return $this->hasOne(VegetableLand::class, "id", "land_id");
    }

    function user()
    {
        return $this->hasOne(MemberInfo::class, "id", "m_id");
    }
}
